name: Build Package
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      libraries:
        type: string
        required: true
      registry-url:
        type: string
        default: "https://npm.pkg.github.com"

jobs:
  build:
    runs-on:
      group: arc-runners

    steps:
      - name: Install `gh` cli
        run: |
          #!/bin/bash -ex
          sudo apt-get update
          sudo apt-get install -y gh

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
  
      - uses: actions/download-artifact@v4
        with:
          name: h402-dist
          path: typescript/packages/h402/dist

      - uses: actions/download-artifact@v4
        with:
          name: h402-node_modules
          path: typescript/packages/h402/node_modules

      - name: Install Libraries
        run: |
          #!/bin/bash -ex

          echo '${{ inputs.libraries }}' | \
          jq -r '.[]' | \
          while read -r library; do
            gh run download \
              ${{ github.run_id }} \
              -n "${library}-dist" \
              --dir "typescript/packages/${library}/dist"

            gh run download \
              ${{ github.run_id }} \
              -n "${library}-node_modules" \
              --dir "typescript/packages/${library}/node_modules"
          done
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: ${{ inputs.registry-url }}
          scope: "@bit-gpt"
          cache: "pnpm"

      - name: Build
        run: |
          cd ./typescript/packages/${{ inputs.name }}
          pnpm --filter '@bit-gpt/${{ inputs.name }}' i
          pnpm --filter '@bit-gpt/${{ inputs.name }}' build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-dist
          path: typescript/packages/${{ inputs.name }}/dist
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-node_modules
          path: typescript/packages/${{ inputs.name }}/node_modules
          if-no-files-found: error
