name: Deploy Example

on:
  workflow_dispatch:
  push:
    paths:
      - 'typescript/example/**'

jobs:
  build:
    runs-on: [self-hosted]

    permissions:
      contents: read
      packages: read

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

      - uses: actions/checkout@v4

      - uses: docker/build-push-action@v6 
        with:
          context: "{{defaultContext}}:typescript/example"
          tags: |
            ${{ secrets.REGISTRY_URL }}/h402/example:latest
            ${{ secrets.REGISTRY_URL }}/h402/example:${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-envs: |
            npm-token=NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-metadata: read
          owner: ${{ github.repository_owner }}
          #repositories: |
          #  manifests
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: bit-gpt/manifests
          event-type: deploy
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "path": "h402/example/overlays/dev",
              "sha": "${{ github.sha }}",
              "images": {
                "example": "${{ secrets.REGISTRY_URL }}/h402/example:${{ github.sha }}"
              }
            }
